version: '3'
services:
  rabbitmq:
    image: "rabbitmq:3.8-management-alpine"
    ports:
      - 5672:5672
      - 8080:15672
    restart: unless-stopped
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
  elasticsearch:
    image: elasticsearch:7.6.1
    ports:
      - 9200:9200
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=password
  saver:
    build:
      context: .
      args:
        GITHUB_TOKEN: $GITHUB_TOKEN
    depends_on:
      - rabbitmq
      - elasticsearch
    restart: unless-stopped
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=user
      - RABBITMQ_PASSWORD=password
      - RABBITMQ_APP_ID=sizematch-items-saver
      - CONSUMER_QUEUE_NAME=sizematch-items-saver
      - PREFETCH_COUNT=2
      - ELASTICSEARCH_URLS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=password
      - ELASTICSEARCH_MAX_RETRIES=3
      - INDEX_NAME=sizematch-items
